### ISSUE TITLE
Media foundation libraries

### ISSUE THREAD

**Issue by SwooshyCueb** [GloriousEggroll/wine-ge-custom#1]
Opening this issue here since your protonfixes repo doesn't have an issue tracker.

I may have figured out a way to get some of the dlls you had to remove from the `mf_install` verb directly from microsoft. It will require extracting them from newer update msu packages,
which use [Intra-Package Delta](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc722332(v=ws.10)?redirectedfrom=MSDN) compression.
When the msu's cab file is extracted with `cabextract` or 7z, you'll get a `_manifest_.cix.xml` and a bunch of delta files, which aren't very useful in their
current form.

In the past, I have had success extracting these update packages using native `cabinet.dll`, `dpx.dll`, `msdelta.dll`, and `expand.exe`. But this is where things
get tricky.  
`expand.exe` does not exist within any publicly available update packages (or at least none that I can find). And while I bet we could script pulling a windows 10 ESD from microsoft's servers and
extracting it from the image, that seems like overkill. In fact, all we really need is the `msdelta.dll`, which `winetricks` helpfully already provides via a handy
`msdelta` verb already, which extracts it from the Windows 7 SP1 update package.

For the sake of completeness, I feel I should note here that `cabinet.dll`, and `dpx.dll` can both also be found in the Windows 7 SP1 update package.

By parsing `_manifest_.cix.xml`, we can figure out what we need to do to finish the extraction. At some point in the past (I cannot find the code I wrote for this
for the life of me) I wrote a winetricks verb that would parse the `_manifest_.cix.xml` and use `w_ahk_do` to `DllCall` into `msdelta.dll` to finish the
extraction.

Here's the documentation for the functions in `msdelta.dll`: https://docs.microsoft.com/en-us/previous-versions/bb417345(v=msdn.10)?redirectedfrom=MSDN#msdelta-reference 
There used to be more, but microsoft decided it wasn't worth keeping around, I guess.

At some point later this week, if I can find the motivation/energy, I'll try and figure out some way to get this functionality into protonfixes.

[kb968211](https://www.microsoft.com/en-us/download/details.aspx?id=16546) contains every dll that was removed from `mf_install.verb`, with the exception of `msmpeg2adec.dll` and `msmpeg2vdec.dll`.  
[kb3110329](https://www.catalog.update.microsoft.com/Search.aspx?q=3110329) contains `msmpeg2adec.dll` and `msmpeg2vdec.dll`.  
The above packages also contain several other libraries and such that might be useful.  
`msmpeg2adec.dll` and `msmpeg2vdec.dll` can also be found in [every cumulative update for Windows 10 1511 since kb3124262](https://www.catalog.update.microsoft.com/Search.aspx?q=cumulative%20update%20for%20windows%2010%201511). The latest is [kb4093109](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4093109)

**Comment by GloriousEggroll** [comment]
Thanks man, this is definitely useful information, and yeah this would
definitely be able to be added if possible. While official proton may not
be able to do it, it would at least allow the repo to have these fixes
without crossing any lines since the dlls would be directly from microsoft.
If you can figure out the extraction method I'm sure we could easily get it
added. Ill see if I can forward this over to a few other people to as they
might also  have some ideas.

**Comment by SwooshyCueb** [comment]
I had a few minutes to myself at work today, so I took a look at dpx.dll and the relevant files in the Windows 7 SDK (`dpx.h` and `dpx1.idl`) and threw [this](https://gist.github.com/SwooshyCueb/66a06752972748ca84ff219cdd58ca00) together.  
It's a quick and dirty C++ console program that will extract an IPD cab. (Dpx uses COM, so you might run into trouble if you try to compile it with g++.) I'm still not sure if this would be the best approach to tackle this issue, but it's another avenue to explore. I might see if I can't set up a proper repo for it this weekend.

**Comment by GloriousEggroll** [comment]
Thanks I'll def take a look when I get a moment. I've also noticed msu file
extraction patches were added to wusa in wine recently and staging has
re-enabled the wusa package installer patchset, unsure if this is useful as
I haven't tested it yet, but may be something work looking into:

https://github.com/wine-mirror/wine/commit/9934b25313e1a54ea3bd96b38c748ba86ab3fb5f
https://github.com/wine-mirror/wine/commit/bf46a167114ce24712c56a9c050ed216dfeaf671
https://github.com/wine-mirror/wine/commit/45b59c85cae39d6d658aa8aea2ba3921dcf6d55c
https://github.com/wine-mirror/wine/commit/dbfd99e177841bdf722a90b45a24b823912acf9b

https://github.com/wine-staging/wine-staging/commit/f23d30bc06e3c9164cc0489d2241c230a9c0912b

**Comment by SwooshyCueb** [comment]
Yeah I saw that. Unfortunately, there's no support for msdelta currently.
https://github.com/wine-mirror/wine/blob/dbfd99e177841bdf722a90b45a24b823912acf9b/programs/wusa/main.c#L373
https://github.com/wine-staging/wine-staging/blob/2f95fb478268eb63d18f405f6b6d00f778a41ca0/patches/wusa-MSU_Package_Installer/0007-wusa-Print-warning-when-encountering-msdelta-compres.patch#L27

**Comment by GloriousEggroll** [comment]
I was trying to see if I could compile this via mingw but running into an
issue. I was able to extract dpx.dll from the win 7 sdk, but I wasn't able
to find dpx.h anywhere to extract along with it, maybe I need a different
package? unsure.
I'm using GRMSDK_EN_DVD win 7 sdk ISO, and attempting using following:

x86_64-w64-mingw32-g++ dpexpand.cpp -o dpexpand -L. -ldpx

**Comment by SwooshyCueb** [comment]
I'd be very surprised if this builds with mingw.

dpx.h is in the windows 7 sdk. dunno where on the ISO, but here it is in a mirror someone made:
https://github.com/nihon-tc/Rtest/blob/master/header/Microsoft%20SDKs/Windows/v7.0A/Include/dpx.h
dpx.h includes dpx1.h, which includes various other header files, so you'll probably have to grab several.

**Comment by PietJankbal** [comment]
> `expand.exe` does not exist within any publicly available update packages (or at least none that I can find).

SwooshyCueb, nice info.  I just needed this (for extracting another thing from  diffenent tmsu)
I quickly fixed up winetricks script. That worked for me to extract files from msu file. The expand.exe is present in Windows6.0-KB936330-X64-wave0.exe 


helper_winvista()
{
    filename=$1

    if test -f "$W_CACHE/winvista/Windows6.0-KB936330-X64-wave0.exe"; then
        echo "Windows6.0-KB936330-X64-wave0.exe exists, skipping download ...."
    else
        w_download_to winvista https://download.microsoft.com/download/8/3/b/83b8c814-b000-44a4-b667-8c1f58727b8b/Windows6.0-KB936330-X64-wave0.exe # b7976e24d19d2aade5491514b9af3aeee6d095c774eec846fbbc21348389d593
    fi

    cabextract -d "$W_TMP/winvista" -F   "$filename" "$W_CACHE/winvista/Windows6.0-KB936330-X64-wave0.exe"
}



w_metadata expand dlls


load_expand()
{   
    echo "$W_PROGRAMS_UNIX"
    echo "$W_PROGRAMS_X86_UNIX"

    

    w_override_dlls native expand.exe msdelta cabinet dpx


    for i in x86_microsoft-windows-basic-misc-tools_31bf3856ad364e35_6.0.6001.18000_none_175cb770bf6b8f77/expand.exe \
        x86_microsoft-windows-deltapackageexpander_31bf3856ad364e35_6.0.6001.18000_none_69de962f3507db4b/dpx.dll \
        x86_microsoft-windows-cabinet_31bf3856ad364e35_6.0.6001.18000_none_373f511ce1ebb446/cabinet.dll \
        x86_microsoft-windows-servicingstack_31bf3856ad364e35_6.0.6001.18000_none_095f6148c74a7a64/msdelta.dll

    do
        helper_winvista "$i"
        w_try cp "$W_TMP/winvista/$i" "$W_SYSTEM32_DLLS/"
    done



    if [ "$W_ARCH" = "win64" ]; then

        for i in amd64_microsoft-windows-basic-misc-tools_31bf3856ad364e35_6.0.6001.18000_none_737b52f477c900ad/expand.exe \
            amd64_microsoft-windows-deltapackageexpander_31bf3856ad364e35_6.0.6001.18000_none_c5fd31b2ed654c81/dpx.dll \
            amd64_microsoft-windows-cabinet_31bf3856ad364e35_6.0.6001.18000_none_935deca09a49257c/cabinet.dll \
            amd64_microsoft-windows-deltacompressionengine_31bf3856ad364e35_6.0.6001.18000_none_9c4b039c3e1c8af8/msdelta.dll

    do
        helper_winvista "$i"
        w_try cp "$W_TMP/winvista/$i" "$W_SYSTEM64_DLLS/"
    done
    fi   

    echo "Example of usage: expand -F:* some.msu "C:\tmp" "
    echo "cd "c:\tmp" "
    echo "expand -F:* some.cab "C:\tmp""
}

**Comment by GloriousEggroll** [comment]
closing as we are focusing on mfplat patches in staging rather than using mfplat from windows
